name: tests

on:
  pull_request:
    branches:
      - "15.0"
  push:
    branches:
      - "15.0"

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ghcr.io/oca/oca-ci/py3.8-odoo15.0:latest
    name: test with Odoo
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install addons and dependencies
        run: oca_install_addons
      - name: Initialize test db
        run: oca_init_test_database
      - name: Run tests
        run: oca_run_tests
      - uses: codecov/codecov-action@v1
